# For an explanation of these settings, visit https://github.com/ltguide/CraftBukkit-MineBackup/wiki/Configuration

default_actions:
  save: true
  copy: false
  compress: false
  cleanup: false
  dropbox: false
  ftp: false
default_settings:
  save: 15m
  copy: 1h
  compress: 1h
  compression_level: 9
  cleanup: '2:00'
  dropbox: '3:00'
  ftp: '3:30'
  keep: 24
worlds:
  yourworldname:
    save: true
    compress: true
  yourworldname_nether:
    save: 30m
    compress: 3h
    keep: 8
  yourworldname_the_end:
    save: 30m
    copy: 6h
    keep: 4
others:
  plugins:
    copy: false
    compress: false
    dropbox: false
    exclude-folders:
      - tiles
    exclude-types:
      - jar
      - lck
directories:
  worlds: .
  others: .
  destination: ./minebackup
destination:
  format: '%Y-%M-%D_%H-%m-%S'
  prepend-world: false
ftp:
  server: 'ftpserver:21'
  path: '/'
  username: 'user'
  password: '123'
messages:
  prefix: '&e[MineBackup]&f'
  syntax: '&6Syntax: &f%s &6--&e %s'
  permission: '&cYou do not have permission.'
  reload: '&aReloaded configuration. (%s)'
  busy: 'An action is currently in progress. Try again in a few seconds.'
  status: '&6%s: &f%s (&edirty: &f%s) %s'
  status_action: '&6%s: &f%s (&e%s&f)&6; '
  status_time_under: 'waiting %s'
  status_time_over: 'soon (%s over)'
  status_time_none: 'not scheduled'
  status_note: 'New actions will be scheduled once a minute.'
  backup_now: 'All backup actions will start momentarily. (%s)'
  backup_soon: 'All backup actions added to the queue. (%s)'
  backup_next: 'The next backup action has been started early. (%s)'
  backup_done: 'All backup actions have completed.'
  dropbox: 'Dropbox authentication completed. (%s)'
commands:
  status:
    description: 'Display the scheduled time and interval for each action in the queue.'
  now:
    description: 'Expire all action times and trigger them NOW.'
    broadcast: users
  soon:
    description: 'Expire all action times so that they will trigger on the following queue checks.'
    broadcast: admins
  next:
    description: 'Trigger the next action in the queue. If no time is expired then nothing will happen.'
    broadcast: admins
  reload:
    description: 'Reload configuration and reset queue to configured intervals.'
    broadcast: false
  dropbox:
    description: 'Add Dropbox authentication tokens. Visit https://minebackup-dropbox.appspot.com/ for values.'
    broadcast: false
debug: false
start_covered_in_dirt: false
version-nomodify: '0.5.8'
